export default [
    {
        id:0,
        title:"亚洲基础设施投资银行总部永久办公场所项目B标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:1,
        others:52,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目B标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久",
                title:"亚投行-现场临设",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久",
                title:"亚投行-现场临设",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久",
                title:"亚投行-现场临设",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久",
                title:"亚投行-现场临设",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久",
                title:"亚投行-现场临设",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久",
                title:"亚投行-现场临设",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        zulin:[],
        qita:[]
    },
    {
        id:1,
        title:"亚洲基础设施投资银行总部永久办公场所项目A标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:3,
        others:38,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[],
        zulin:[],
        qita:[]
    },
    {
        id:2,
        title:"亚洲基础设施投资银行总部永久办公场所项目A标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:3,
        others:38,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[],
        zulin:[],
        qita:[{
            name:"亚洲基础设施投资银行总部",
            sum:"1,250,000",
            metering:"198,000",
            payment:"198,000",
            subContractor:"北京安机电设备安装工程有限公司",
            Corp:"李胖"  
        }]
    },
    {
        id:3,
        title:"亚洲基础设施投资银行总部永久办公场所项目A标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:3,
        others:38,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[],
        zulin:[{
            name:"亚洲基础设施投资银行总部",
            sum:"1,250,000",
            metering:"198,000",
            payment:"198,000",
            subContractor:"北京安机电设备安装工程有限公司",
            Corp:"李胖"  
        }],
        qita:[]
    },
    {
        id:4,
        title:"亚洲基础设施投资银行总部永久办公场所项目A标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:3,
        others:38,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[],
        zulin:[],
        qita:[]
    },
    {
        id:5,
        title:"亚洲基础设施投资银行总部永久办公场所项目A标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:3,
        others:38,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[],
        zulin:[],
        qita:[]
    },
    {
        id:6,
        title:"亚洲基础设施投资银行总部永久办公场所项目A标段",
        pro:"工程总承包部",
        address:"北京市朝阳区奥林匹克公园B27-2地块",
        total:3,
        others:38,
        totals:[//总包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                cost:"1,2000,000,000",
                measure:"800,000,000",
                stating:"2017-04-10",
                end:"2019-07-28",
                days:"839",
                contractDate:"2017-04-10",
                danwei:"北京城市副中心投资件事集团有限公司"
            }
        ],
        professionals:[//专业分包
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },{
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            },
            {
                name:"亚洲基础设施投资银行总部永久办公场所项目A标段",
                sum:"4,250,000",
                metering:"3,198,000",
                payment:"3,198,000",
                subContractor:"北京鑫泰德安机电设备安装工程有限公司",
                Corp:"李勇"
            }
        ],
        subcontractors:[//劳务分包
            {
                name:"亚洲基础设施投资银行总部",
                sum:"1,250,000",
                metering:"198,000",
                payment:"198,000",
                subContractor:"北京安机电设备安装工程有限公司",
                Corp:"李胖"  
            }
        ],
        cagou:[{
            name:"亚洲基础设施投资银行总部",
            sum:"1,250,000",
            metering:"198,000",
            payment:"198,000",
            subContractor:"北京安机电设备安装工程有限公司",
            Corp:"李胖"  
        }],
        zulin:[{
            name:"亚洲基础设施投资银行总部",
            sum:"1,250,000",
            metering:"198,000",
            payment:"198,000",
            subContractor:"北京安机电设备安装工程有限公司",
            Corp:"李胖"  
        }],
        qita:[{
            name:"亚洲基础设施投资银行总部",
            sum:"1,250,000",
            metering:"198,000",
            payment:"198,000",
            subContractor:"北京安机电设备安装工程有限公司",
            Corp:"李胖"  
        }]
    }
]
;